---
services:
  chrome-81:
    image: gitsang/chrome:81.0.4044.92-20251103
    build:
      context: .
      dockerfile: Dockerfile.google-chrome_81.0.4044.92
    container_name: chrome-81
    restart: unless-stopped
    shm_size: "512mb"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /etc/fonts:/etc/fonts
      - /usr/share/fonts:/usr/share/fonts
      - ./data/chrome-81:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.to-chrome-81.rule=Host(`chrome-81.${DOMAIN}`)"
      - "traefik.http.routers.to-chrome-81.tls.certResolver=ali_resolver"
      - "traefik.http.routers.to-chrome-81.service=chrome-81"
      - "traefik.http.services.chrome-81.loadBalancer.server.port=3000"

  chrome-86:
    image: gitsang/chrome:86.0.4240.75-20251104
    build:
      context: .
      dockerfile: Dockerfile.google-chrome_86.0.4240.75
    container_name: chrome-86
    restart: unless-stopped
    shm_size: "512mb"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /etc/fonts:/etc/fonts
      - /usr/share/fonts:/usr/share/fonts
      - ./data/chrome-86:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.to-chrome-86.rule=Host(`chrome-86.${DOMAIN}`)"
      - "traefik.http.routers.to-chrome-86.tls.certResolver=ali_resolver"
      - "traefik.http.routers.to-chrome-86.service=chrome-86"
      - "traefik.http.services.chrome-86.loadBalancer.server.port=3000"
